# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67ba9eaea468cbc0bb22f6ec7e70fc10e598a9c42ec2cfcc1b5396ba31c5d91abbcbdc04ee5e4a4250f8b30a3c7a7084e5ca1fd965e97583726e0d168fdc1f88

test:
  secret_key_base: 6f2f8095b87601a300a34cc133945114d153054bd3fd89dc62aef96d0ee7912d8afe3ad6d00c670bd392011c04980313d6d63456c76e4b0d71c35aac76b5fd23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
